theme: jekyll-theme-minimal
logo: media/images/kick_comp.png
title: Sec 4 Non-Tech
description: "A blog for the non-technical types.  Born from stories of friends being hacked,
falling for phishing attacks and a general misunderstanding of the tech people use on a minutely
basis."
