theme: jekyll-theme-minimal
markdown: kramdown
logo: assets/images/kick_comp.png
title: SEC 4 NON-TECH
description: "A blog for the non-technical types.  Born from stories of friends being hacked,
falling for phishing attacks and a general misunderstanding of the tech people use everyday."
